### ISSUE TITLE
[Backend] Добавить endpoint на регистрацию

### ISSUE THREAD

**Issue by Awakenlive** [HSE-collaboratorium/medical-assistant#14]
### Задача

- [ ] Добавить ручку на регистрацию (создание пользователя в бд)
- [ ] Пароль перед тем как положить в базу зашифровать

**Comment by Xopppek** [comment]
Регистрация нового пользователя доступна в эндпоинте user/register
post запросом передаются email и password

При успешном добавлении возвращаются id и email добавленного пользователя (возможно id возвращать не нужно)
