### ISSUE TITLE
[Android] Проектирование архитектуры

### ISSUE THREAD

**Issue by NewRonin** [HSE-collaboratorium/medical-assistant#4]
**Задача**

1. Выбрать target версию ОС.
2. Выбрать конечный стек.
3. Создать проект
4. Подключить все необходимые зависимости и библиотеки. 

Критерии приёмки:
- выбранная версия представлена в комментариях к задаче в срок
- выбранный стек представлен в комментариях к задаче в срок

**Comment by Awakenlive** [comment]
Выбрал Clean architecture с использованием MVVM, так как MVVM будет легче для новичков. Создал папки под это

Подключил зависимости:

1. Hilt
2. Retrofit
3. Compose Navigation
4. Lifecycle
5. ViewModel
6. Coroutines
7. Compose
